services:
  qwen3-omni-vllm:
    image: xproger/qwen3-omni-nvfp4-vllm:latest
    container_name: qwen3-omni-vllm
    gpus: all
    ipc: host
    shm_size: "8g"
    ports:
      - "18089:18089"
    volumes:
      - /home/vladimir/ai-models/llm/Qwen3-Omni-30B-A3B-Instruct-NVFP4:/models/Qwen3-Omni-30B-A3B-Instruct-NVFP4
    environment:
      MODEL_ROOT: /models/Qwen3-Omni-30B-A3B-Instruct-NVFP4
      MODEL_DIR: /models/Qwen3-Omni-30B-A3B-Instruct-NVFP4/thinker
      TOKENIZER_DIR: /models/Qwen3-Omni-30B-A3B-Instruct-NVFP4
      HF_CONFIG_PATH: /models/Qwen3-Omni-30B-A3B-Instruct-NVFP4/vllm-root-config
      SERVED_MODEL_NAME: qwen3-omni-nvfp4-thinker
      PORT: "18089"
      MAX_MODEL_LEN: "8192"
      MAX_NUM_SEQS: "1"
      MAX_NUM_BATCHED_TOKENS: "4096"
      GPU_MEMORY_UTILIZATION: "0.90"
      MOE_BACKEND: marlin
      VLLM_NVFP4_GEMM_BACKEND: marlin
